apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ibmstreamsjobs.ibmstreamsjob.operator.bmwilli
spec:
  group: ibmstreamsjob.operator.bmwilli
  names:
    kind: IBMStreamsJob
    listKind: IBMStreamsJobList
    plural: ibmstreamsjobs
    singular: ibmstreamsjob
    shortNames:
      - streamsjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      spec:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        properties:
          sab:
            type: string
        required:
          - sab
  versions:
  - name: v1
    served: true
    storage: true
  additionalPrinterColumns:
    - name: State
      type: string
      description: The state of the IBM Streams IBMStreams job kubernetes object
      JSONPath: .status.k8s_state
    - name: Status
      type: string
      description: The status of the IBM Streams IBMStreams job
      JSONPath: .status.job_status
    - name: Health
      type: string  
      description: The aggregated health of PEs in IBM Streams job
      JSONPath: .status.job_health
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp      