apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ibmstreamsjobs.ibmstreamsjob.operator.bmwilli
spec:
  group: ibmstreamsjob.operator.bmwilli
  names:
    kind: IBMStreamsJob
    listKind: IBMStreamsJobList
    plural: ibmstreamsjobs
    singular: ibmstreamsjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true